// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RentalPropertyManagement.DAL.Data;

#nullable disable

namespace RentalPropertyManagement.DAL.Migrations
{
    [DbContext(typeof(RentalDbContext))]
    [Migration("20251218032606_Demo01")]
    partial class Demo01
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("RentalPropertyManagement.DAL.Entities.Contract", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("PropertyId")
                        .HasColumnType("int");

                    b.Property<decimal>("RentAmount")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("TenantId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PropertyId");

                    b.HasIndex("TenantId");

                    b.ToTable("Contracts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EndDate = new DateTime(2026, 12, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PropertyId = 1,
                            RentAmount = 10000000m,
                            StartDate = new DateTime(2025, 12, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 1,
                            TenantId = 2
                        });
                });

            modelBuilder.Entity("RentalPropertyManagement.DAL.Entities.MaintenanceRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AssignedProviderId")
                        .HasColumnType("int");

                    b.Property<string>("AttachmentUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Priority")
                        .HasColumnType("int");

                    b.Property<int>("PropertyId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime>("SubmittedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("TenantId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AssignedProviderId");

                    b.HasIndex("PropertyId");

                    b.HasIndex("TenantId");

                    b.ToTable("MaintenanceRequests");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AttachmentUrl = "example.jpg",
                            Description = "Fix leaking roof",
                            Priority = 3,
                            PropertyId = 1,
                            Status = 1,
                            SubmittedDate = new DateTime(2025, 12, 18, 10, 26, 6, 274, DateTimeKind.Local).AddTicks(8573),
                            TenantId = 2
                        });
                });

            modelBuilder.Entity("RentalPropertyManagement.DAL.Entities.Property", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsOccupied")
                        .HasColumnType("bit");

                    b.Property<decimal>("MonthlyRent")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int>("SquareFootage")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Properties");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "123 Main St",
                            City = "Hanoi",
                            Description = "Apartment in city center",
                            IsOccupied = false,
                            MonthlyRent = 10000000m,
                            SquareFootage = 100
                        },
                        new
                        {
                            Id = 2,
                            Address = "456 Elm St",
                            City = "Saigon",
                            Description = "House with garden",
                            IsOccupied = true,
                            MonthlyRent = 15000000m,
                            SquareFootage = 150
                        });
                });

            modelBuilder.Entity("RentalPropertyManagement.DAL.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "landlord@gmail.com",
                            FirstName = "Landlord",
                            LastName = "Admin",
                            PasswordHash = "$2y$10$tlwzkAKGJOgk8yPycei6O.ZK4XloYY2mj.G91apzS7sJyn1x3vXn2",
                            PhoneNumber = "0123456789",
                            Role = 1
                        },
                        new
                        {
                            Id = 2,
                            Email = "tenant@gmail.com",
                            FirstName = "Tenant",
                            LastName = "User",
                            PasswordHash = "$2y$10$tlwzkAKGJOgk8yPycei6O.ZK4XloYY2mj.G91apzS7sJyn1x3vXn2",
                            PhoneNumber = "0987654321",
                            Role = 2
                        },
                        new
                        {
                            Id = 3,
                            Email = "provider@gmail.com",
                            FirstName = "Service",
                            LastName = "Provider",
                            PasswordHash = "$2y$10$tlwzkAKGJOgk8yPycei6O.ZK4XloYY2mj.G91apzS7sJyn1x3vXn2",
                            PhoneNumber = "0112233445",
                            Role = 3
                        });
                });

            modelBuilder.Entity("RentalPropertyManagement.DAL.Entities.Contract", b =>
                {
                    b.HasOne("RentalPropertyManagement.DAL.Entities.Property", "Property")
                        .WithMany("Contracts")
                        .HasForeignKey("PropertyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RentalPropertyManagement.DAL.Entities.User", "Tenant")
                        .WithMany("ContractsAsTenant")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Property");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("RentalPropertyManagement.DAL.Entities.MaintenanceRequest", b =>
                {
                    b.HasOne("RentalPropertyManagement.DAL.Entities.User", "AssignedProvider")
                        .WithMany("AssignedRequests")
                        .HasForeignKey("AssignedProviderId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("RentalPropertyManagement.DAL.Entities.Property", "Property")
                        .WithMany("MaintenanceRequests")
                        .HasForeignKey("PropertyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RentalPropertyManagement.DAL.Entities.User", "Tenant")
                        .WithMany("SubmittedRequests")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AssignedProvider");

                    b.Navigation("Property");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("RentalPropertyManagement.DAL.Entities.Property", b =>
                {
                    b.Navigation("Contracts");

                    b.Navigation("MaintenanceRequests");
                });

            modelBuilder.Entity("RentalPropertyManagement.DAL.Entities.User", b =>
                {
                    b.Navigation("AssignedRequests");

                    b.Navigation("ContractsAsTenant");

                    b.Navigation("SubmittedRequests");
                });
#pragma warning restore 612, 618
        }
    }
}
